logging:
  level:
    jdbc:
      connection: info
      resultsettable: info
      sqlonly: info
      sqltiming: info
    root: info

mybatis:
  mapper-locations: classpath:mappers/**/*.xml

server:
  servlet:
    context-path:

spring:
  application:
    name: studyProject

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community
    username: wnsgud1997
    password: 1234

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  servlet:
    multipart:
      location: uploads/
      max-file-size: 10MB
      enabled: true

jwt:
  issuer: jun
  secret: 4XudNUpSmog3lwI9thJFejF7YfBB0517

file:
  upload:
    path: uploads/
